import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const NavItem = [
  { href: "/representatives", label: "Representatives" },
  { href: "/petitions", label: "Petitions" },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <nav className="px-8 py-4 bg-slate-700 text-white sticky top-0">
          <ul className="flex gap-4">
            {NavItem.map((navItem) => (
              <li key={navItem.href}>
                <Link href={navItem.href}>{navItem.label}</Link>
              </li>
            ))}
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
